# -*- coding: utf-8 -*-
"""calculadora_com_opcao_sair.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gmvHc16z1z13muGNpOjVW_ZWJRGxnXZC
"""

def caluladora(numero1, numero2, operacao):

  if (operacao == 1):
    resultado = (numero1 + numero2)
    return resultado

  elif (operacao == 2):
    resultado = (numero1 - numero2)
    return resultado

  elif (operacao == 3):
    resultado = (numero1 * numero2)
    return resultado

  elif (operacao == 4):
    if(numero2 == 0):
      return "Não é possível dividir por zero!"
    resultado = (numero1 / numero2)
    return resultado

  elif(operacao == 0):
    return "Fim do Algorítimo"

  else: return "Essa opção não existe!"

operacao = 1

while(operacao != 0):
  print("--------------------------------------------")
  print("Operações::")
  print("1. Soma")
  print("2. Subtração")
  print("3. Multiplicação")
  print("4. Divisão")
  print("0. Sair")

  numero1 = int(input("Informe o primeiro número: "))
  numero2 = int(input("Informe o primeiro número: "))
  operacao = int(input("Informe a operação desejada: "))

  resultado = caluladora(numero1,numero2, operacao)

  print("\nO Resultado da operação é: ", resultado)