# -*- coding: utf-8 -*-
"""calculadora_com_opcao_sair.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gmvHc16z1z13muGNpOjVW_ZWJRGxnXZC

Faça uma função calculadora que os números e as operações serão feitas pelo usuário. O código deve ficar rodando infinitamente até que o usuário escolha a opção de sair. No início, o programa mostrará a seguinte lista de operações:

1: Soma 2: Subtração 3: Multiplicação 4: Divisão 0: Sair

Digite o número para a operação correspondente e caso o usuário introduza qualquer outro, o sistema deve mostrar a mensagem “Essa opção não existe” e voltar ao menu de opções.

Após a seleção, o sistema deve pedir para o usuário inserir o primeiro e segundo valor, um de cada. Depois precisa executar a operação e mostrar o resultado na tela. Quando o usuário escolher a opção “Sair”, o sistema irá parar.
"""

def caluladora(numero1, numero2, operacao):

  if (operacao == 1):
    resultado = (numero1 + numero2)
    return resultado

  elif (operacao == 2):
    resultado = (numero1 - numero2)
    return resultado

  elif (operacao == 3):
    resultado = (numero1 * numero2)
    return resultado

  elif (operacao == 4):
    if(numero2 == 0):
      return "Não é possível dividir por zero!"
    resultado = (numero1 / numero2)
    return resultado

  elif(operacao == 0):
    return "Fim do Algorítimo"

  else: return "Essa opção não existe!"

operacao = 1

while(operacao != 0):
  print("--------------------------------------------")
  print("Operações::")
  print("1. Soma")
  print("2. Subtração")
  print("3. Multiplicação")
  print("4. Divisão")
  print("0. Sair")

  numero1 = int(input("Informe o primeiro número: "))
  numero2 = int(input("Informe o segundo número: "))
  operacao = int(input("Informe a operação desejada: "))

  resultado = caluladora(numero1,numero2, operacao)

  print("\nO Resultado da operação é: ", resultado)