# -*- coding: utf-8 -*-
"""Aula 5 - Exercício 1 a 5 - Atividades Extras.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sh_kFUuk1z4mLfYeIiJsqgpUuFtFuTqL

#ESTRUTURAS DE REPETIÇÃO

1.   Regras todas as plantas

* FOR
"""

for i in range(6):
  planta_atual = str(i)
  print("Regar a planta: " + planta_atual)

"""* WHILE"""

contador = 0

while(contador < 6):
  planta_atual = str(contador)
  print("Regar a planta: " + planta_atual)
  contador += 1

"""2.   Regar Pares - Tutora

"""

for i in range(6):
  if(i %  2 != 0):
    continue
  print("Regar a planta: " + str(i))

"""2.   Regar Pares - Aluno"""

contador = 0

while(contador < 6):
  if(contador % 2 == 0):
    print("Regar a planta: " + str(contador))
  contador += 1

"""3.   Regar Batatas

"""

for contador in range(6):
  if(contador < 3):
    continue
  print("Regar a planta: " + str(contador))
  contador += 1

"""4.   Regar Tomates

"""

for contador in range(6):
  if(contador == 2) or (contador == 3 ):
    continue
  print("Regar a planta: " + str(contador))
  contador += 1

"""5.   Regar de trás pra frente

"""

for contador in range(5, -1, -1):
  print("Regar a planta: " + str(contador))