# -*- coding: utf-8 -*-
"""funções.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15_WcR6gmjFi_z7hSbxJzHswJnHCEC4yo
"""



"""felipe ribeiro//
braulio//
wandeyson Clayton//
Lenadro//
sabrina//

atualizem ai meu teams caiu kkk
"""

def divisao(num1, num2):
  resultado = str(num1 / num2)
  frase = str(num1) + ' / ' + str(num2) + ' = ' + resultado
  return frase

print(divisao(10,2))

for i in range(1, 13):
  frase_atual = divisao(8, i)
  print (frase_atual)

def soma(num1, num2):
  resultado = str(num1 + num2)
  frase = str(num1) + ' + ' + str(num2) + ' = ' + resultado
  return frase
print(soma(10,2))

for i in range(1, 13):
  frase_atual = soma(8, i)
  print (frase_atual)

def subtracao(num1, num2):
  resultado = str(num1 - num2)
  frase = str(num1) + ' - ' + str(num2) + ' = ' + resultado
  return frase
print(subtracao(10,2))

for i in range(1, 13):
  frase_atual = subtracao(8, i)
  print (frase_atual)