# -*- coding: utf-8 -*-
"""Teste.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NklG6uuKmCmkXVZqaBfj4DLbDZrCx2ih
"""

lista_frutas = ['melancia', 'morango', 'abacaxi']
print(lista_frutas)
# Imprimirá: ['melancia', 'morango', 'abacaxi']

lista_frutas.append('kiwi')
print(lista_frutas)
# Imprimirá: ['melancia', 'morango', 'abacaxi', 'kiwi']

lista_num = ['melancia', 'morango', 'abacaxi']

for i in range(len(lista_num)):
  print(lista_num[i])

for i in range(6):
  planta_atual = str(i)
  print("Regar a planta: " + planta_atual)

lista_num = ['melancia', 'morango', 'abacaxi']

for i in lista_num:
  print(i)

lista_num = ['melancia', 'morango', 'abacaxi']

_ = [print(i) for i in lista_num]

lista_num = ['melancia', 'morango', 'abacaxi']

for i, elem in enumerate(lista_num):
  print(i, ":", elem)

import numpy as np

lista_num = np.arange(10)

for i in np.nditer(lista_num):
  print(i)

lista_frutas = ['melancia', 'morango', 'abacaxi']
print(lista_frutas)
# Imprimirá: ['melancia', 'morango', 'abacaxi']

lista_frutas.append('kiwi')
print(lista_frutas)
# Imprimirá: ['melancia', 'morango', 'abacaxi', 'kiwi']

lista_frutas = ['melancia', 'morango', 'abacaxi', 'kiwi']
print(lista_frutas)
# Imprimirá: ['melancia', 'morango', 'abacaxi', 'kiwi']

lista_frutas.pop()
print(lista_frutas)
# Imprimirá: ['melancia', 'morango', 'abacaxi']

nome = input("Informe seu Nome Completo: ")

ano_valido = False

while(ano_valido == False):
  try:

    ano_nascimento = int(input("Informe o ano do seu nascimento(Entre 1922 e 2021): "))


    if(ano_nascimento >= 1922) and (ano_nascimento <= 2021):
      print("\nO nome do usuário é: " + nome)
      print("Neste ano de 2022 sua idade que completou, ou completará é de: " + str((2022  - ano_nascimento)))
      ano_valido = True
    else:
      print("\nAno de nascimento precisa estar entre 1922 e 2021!")

  except:
    print("\nAno de nascimento inválido!")

for i in range(6):
  if(i %  2 != 0):
    continue
  print("Regar a planta: " + str(i))

for i in range(6):
  if(i %  2 != 0):
    break
  print("Regar a planta: " + str(i))

contador = 0

while(contador < 6):
  planta_atual = str(contador)
  print("Regar a planta: " + planta_atual)
  contador += 1

def escrever_multiplicacao(n1,n2):
   resultado =str(n1 * n2)
   fra = str(n1) + ' X ' + str(n2) + ' = ' + resultado
   return fra
print(escrever_multiplicacao(2, 10))