# -*- coding: utf-8 -*-
"""calculadora_dois_numeros.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yQU0hfy5IQMgYuWzhxOqQ_4JECP_fr1D
"""

def caluladora(numero1, numero2, operacao):

  if (operacao == 1):
    resultado = (numero1 + numero2)
    return resultado

  elif (operacao == 2):
    resultado = (numero1 - numero2)
    return resultado

  elif (operacao == 3):
    resultado = (numero1 * numero2)
    return resultado

  elif (operacao == 4):
    if(numero2 == 0):
      return "Não é possível dividir por zero!"
    resultado = (numero1 / numero2)
    return resultado

  else: return 0



print("Operações::")
print("1. Soma")
print("2. Subtração")
print("3. Multiplicação")
print("4. Divisão")

numero1 = int(input("Informe o primeiro número: "))
numero2 = int(input("Informe o segundo número: "))
operacao = int(input("Informe a operação desejada: "))

resultado = caluladora(numero1,numero2, operacao)

print("O Resultado da operação é: ", resultado)