# -*- coding: utf-8 -*-
"""Aula 4 - Exercício.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/163sup0_ibGKIQwP3yIwdQeo_kvjTiomo

#TIPO DE DADOS
"""

bebidaFavorita = "Cevada"
print(bebidaFavorita)
print(type(bebidaFavorita))

bebida_preco = 12.95
print(bebida_preco)
print(type(bebida_preco))

alcoolica = False
print(alcoolica)
print(type(alcoolica))

print("Minha bebida favorita é: " + bebidaFavorita + " e o valor é: R$ " + str(bebida_preco))

idade = 32
nome = "Danillo"

print("Olá, me chamo {} e tenho {} anos.".format(nome, idade))

"""#OPERADORES"""

almoco_favorito = "Lasanha"
almoco_preco = 26.99

orcamento = 50


total = bebida_preco + almoco_preco
print(total)

print(orcamento - total)
print("Meu Orçamento é: R$ ", orcamento)
print("E o Valor é: R$ ", total)

"""#Exercício

* Declare variáveis para sua sobremesa favorita, o preço dela, e a quantidade de convidados. Na sequência imprima o novo valor total e o valor a ser pago por cada convidado.
"""

sobremesa_favorita = "Pudim"
sobremesa_preco = 14.95
quantidade_convidados = 13
valor_total = ((bebida_preco + almoco_preco + sobremesa_preco) * quantidade_convidados)
valor_por_pessoa = (valor_total / quantidade_convidados)


print("A quantide de convidados é: ", quantidade_convidados)
print(f"O Valor total da conta é: R$ {valor_total:.2f}")
print(f"O Valor por pessoa a ser Pago é: R$ {valor_por_pessoa:.2f}")

"""#ESTRUTURAS CONDICIONAIS

* Vamos Conseguir Pagar o Jantar?
"""

if(orcamento >= valor_por_pessoa):
  print("Vamos dividir a conta!")
else:
  print("Então você não vai acreditar, masss...")

"""* Inclui variável do bom amigo...."""

bom_amigo = True

if(orcamento >= valor_por_pessoa):
    print("Vamos dividir a conta!")
elif(bom_amigo == False):
  print("Obrigado meu amigo!")
else:
  print("Garçom! Será que vocês estão precisando de alguém para lavar os pratos?")