# -*- coding: utf-8 -*-
"""Aula 7 - PBL - Estoque-Produtos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PqiDljKnBG8PF9Z12TOQPbnw5xSQSCFX

#Função que verifica se um array tem determinado elemento ou não
"""

def achar_elemento(elem, arr):
  achou = False

  for i in range(len(arr)):
    if arr[i] == elem:
      achou = True

  if(achou == False):
    print("Não achamos o nome: " + elem)
  else:
    print("Achamos o nome: " + elem)


nomes = ["Rafael", "João", "Karen", "Julia"]

achar_elemento("Rafael", nomes)

"""#1º Desafio:

* O sistema irá perguntar ao usuário o elemento que deseja procurar, e continue procurando até achar um:
"""

def achar_elemento(elem, arr):
  achou = False

  for i in range(len(arr)):
    if arr[i] == elem:
      achou = True

  if(achou == False):
    print("Não achamos o nome: " + elem)
  else:
    print("Achamos o nome: " + elem)


nomes = ["Rafael", "João", "Karen", "Julia"]

elem = input("Informe o Nome Desejado: ")

achar_elemento(elem, nomes)

"""#2º Desafio:

* O dono de uma loja entra em contato com você com a seguinte situação:

"Boa Tarde,

Estamos modernizando nossa loja e precisamos de um novo sistema de controle de estoque.
Geralmente anotamos todos os produtos que temos disponíveis, e quando um dos produtos acaba, substituímos ele por algum outro produto.

Ouvi dizer que vocês podem fazer um sistema para a gente que mostra a lista com todos nossos produtos, e nos deixa alterar um produto por outro.

Além disso, estamos pensando em amplicar nosso armazém, para ter mais espaços apra mais produtos. Então, se puderem fazer com que o sistema nos permita adicionar mais produtos à lista, e qualquer outra coisa que acharem necessário, seria muito bom.

Desde já agradeço!"
"""

def controle_estoque():

  entrada = 0
  estoque = ["Arroz", "Feijão"]
  numero_valido = False

  while (entrada != 4):

    print("==============================")
    print("SISTEMA DE CONTROLE DE ESTOQUE\n\n")

    print("Informe uma das opções:\n")
    print("1 - Para Listar os  Produto do Estoque")
    print("2 - Para Adicionar Produto")
    print("3 - Para Substituir Produto")
    print("4 - Para encerrar Sistema")
    print("==============================")

    try:
      entrada = int(input())
    except:
      print("Você precisa digitar um número inteiro!")

    if (entrada == 1):
      print("ITENS NO ESTOQUE ATUALMENTE:\n")
      for i in range(len(estoque)):
        print(str(i+1) + " - " + estoque[i])

    elif (entrada == 2):
      novo_produto = input("Qual o produto deseja adicionar ao estoque? \n")
      estoque.append(novo_produto)


    elif (entrada == 3):
      while(numero_valido == False):

        try:
          codigo_produto = int(input("Informe o código do produto que deseja substituir:\n")) - 1
          novo_produto = input("Informe o código do produto que deseja substituir:\n")
          estoque[codigo_produto] = novo_produto
          numero_valido = True
        except:
          print("Você precisa digitar um número inteiro!")

  print("***SISTEMA FINALIZADO***")

controle_estoque()