# -*- coding: utf-8 -*-
"""Exception.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HF6OcMr-ulhvCXhRnAOXudWbMbxrWZjS
"""

print("Informe um Número: ")
try:
  valor = int(input())
  valor = valor + 5
  print(str(valor))
except:
  print("Não foi digitado um número!")



print("Informe um Número: ")
try:
  valor = int(input())
  valor = valor + 5
  print(str(valor))
except Exception as e:
  print(e)

def caluladora(numero1, numero2, operacao):

  if (operacao == 1):
    resultado = (numero1 + numero2)


  elif (operacao == 2):
    resultado = (numero1 - numero2)


  elif (operacao == 3):
    resultado = (numero1 * numero2)


  elif (operacao == 4):
    if(numero2 != 0):
      resultado = (numero1 / numero2)
    else:
      raise Exception("Divisão por zero não é possível!")

  else:
    raise Exception("Operação não existe")

  return resultado

operacao = 1

try:
  while(operacao != 0):
    print("--------------------------------------------")
    print("Operações::")
    print("1. Soma")
    print("2. Subtração")
    print("3. Multiplicação")
    print("4. Divisão")
    print("0. Sair")

    numero1 = int(input("Informe o primeiro número: "))
    numero2 = int(input("Informe o segundo número: "))
    operacao = int(input("Informe a operação desejada: "))

    resultado = caluladora(numero1,numero2, operacao)

    print("\nO Resultado da operação é: ", resultado)
except Exception as err:
  print("\nOcorreu um erro:")
  print(err)

numeroCorreto = False

while (numeroCorreto == False):

   print("Insira um número par")

   try:

       numero = int(input())

       if (numero%2 == 0):

           numeroCorreto = True

           print("Você digitou um numero par !")

       else :

           print("Você digitou um número impar")

   except:

       print("Caracter inválido, por favor digite um número par")