# -*- coding: utf-8 -*-
"""Funcao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pSkp3ECpdC-AbmsZXvG6ceIYVHN-EoS6

1-Função multiplicao()
"""

def escrever_multiplicacao(n1,n2):
   resultado =str(n1 * n2)
   fra = str(n1) + ' X ' + str(n2) + ' = ' + resultado
   return fra
print(escrever_multiplicacao(2, 10))



for i in range(1, 13):
  frase_atual = escrever_multiplicacao(8, i)
  print(frase_atual)

def escre_divi(n1,n2):
   resultado1 =str(n1 / n2)
   fra1 = str(n1) + ' / ' + str(n2) + ' = ' + resultado1
   return fra1
for U in range(1, 13):
  frase_atual = escre_divi(10, U)
  print(frase_atual)