# -*- coding: utf-8 -*-
"""Aula 5 - Funções.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x_yvtRPEu7wmljiNgrBIsjWxp5cJ05nH

#FUNÇÕES

* Função Escrever Multiplicação
"""

def escrever_multiplicacao(num1,num2):
  resultado = str(num1 * num2)
  frase = str(num1) + ' x ' + str(num2) + ' = ' + resultado
  return frase

"""* Função Escrever Divisão"""

def escrever_divisao(num1,num2):
  resultado = str(num1 / num2)
  frase = str(num1) + ' ÷ ' + str(num2) + ' = ' + resultado
  return frase

"""* Função Escrever Soma"""

def escrever_soma(num1,num2):
  resultado = str(num1 + num2)
  frase = str(num1) + ' + ' + str(num2) + ' = ' + resultado
  return frase

"""* Função Subtração"""

def escrever_subtracao(num1,num2):
  resultado = str(num1 - num2)
  frase = str(num1) + ' - ' + str(num2) + ' = ' + resultado
  return frase

"""* Utilizando a Multiplicação com For e While"""

print("FOR")
for i in range(1, 13):
  frase_atual  = escrever_multiplicacao(8, i)
  print(frase_atual)

print("WHILE")
contador = 1
while(contador < 13):
  frase_atual  = escrever_multiplicacao(8, contador)
  print(frase_atual)
  contador +=1

"""* Utilizando a Divisão com For e While


"""

print("FOR")
for i in range(1, 13):
  frase_atual  = escrever_divisao(8, i)
  print(frase_atual)

print("WHILE")
contador = 1
while(contador < 13):
  frase_atual  = escrever_divisao(8, contador)
  print(frase_atual)
  contador +=1

"""* Utilizando a Soma com For e While


"""

print("FOR")
for i in range(1, 13):
  frase_atual  = escrever_soma(8, i)
  print(frase_atual)

print("WHILE")
contador = 1
while(contador < 13):
  frase_atual  = escrever_soma(8, contador)
  print(frase_atual)
  contador +=1

"""* Utilizando a Subtração com For e While"""

print("FOR")
for i in range(1, 13):
  frase_atual  = escrever_subtracao(8, i)
  print(frase_atual)

print("WHILE")
contador = 1
while(contador < 13):
  frase_atual  = escrever_subtracao(8, contador)
  print(frase_atual)
  contador +=1