# -*- coding: utf-8 -*-
"""Aula 6 - Input - Tratamento de Erros

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/163klpQDmR-onyzabkZ-OMXB9tc0Wd1Vc

#Tratamento de Erros
"""

def mostrarNumero():
  print("Escreva um número menor ou igual a 100")
  numero_valido = False

  while(numero_valido == False):
    try:
      num = int(input())
      if (num > 100):
        print("O número precisa ser menor que 100")
      else:
        print("Boa! Você escolheu um número menor que 100")
        numero_valido = True
    except:
      print("Você precisa digitar um número inteiro")

mostrarNumero()

"""#Exercício 1

* Verificar se um número é menor que zero, e tratar os erros com as mensagens apropriadas
"""

def mostrarNumero():
  print("Escreva um número maior que zero e menor ou igual a 100")
  numero_valido = False

  while(numero_valido == False):
    try:
      num = int(input())
      if (num > 100):
        print("O número precisa ser menor que 100")
      elif(num < 0):
        print("O número precisa ser maior que zero")
      else:
        print("Boa! Você escolheu um número menor que 100")
        numero_valido = True
    except:
      print("Você precisa digitar um número inteiro")

mostrarNumero()

"""#Exercício 2

* Criar uma segunda função e pedir para o usuário inserir um número par, e tratar os erros com as mensagens apropriadas
"""

def mostrarNumeroPar():
  print("Escreva um número que seja par")
  numero_valido = False

  while(numero_valido == False):
    try:
      num = int(input())
      if (num % 2 != 0):
        print("O número precisa ser par")
      else:
        print("Boa! Você escolheu um número par")
        numero_valido = True
    except:
      print("Você precisa digitar um número inteiro")

mostrarNumeroPar()

"""#Exercício 3

* Pedir um número que seja divisível por 2 e 3, e tratar os erros com as mensagens apropriadas
"""

def mostrarNumeroDivisivel():
  print("Escreva um número que seja divisível por 2 e 3")
  numero_valido = False

  while(numero_valido == False):
    try:
      num = int(input())
      if (num < 0):
        print("O Número precisa ser Maior que zero")
      elif (num % 2 == 0) and (num % 3 != 0):
        print("O número é divisível por 2, mais precisa ser divisível por 3 também")
      elif (num % 2 != 0) and (num % 3 == 0):
        print("O número é divisível por 3, mais precisa ser divisível por 2 também")
      elif (num % 2 == 0) or (num % 3 == 0):
        print("Boa! Você escolheu um divisível por 2 e 3")
        numero_valido = True
      else:
        print("O número precisar ser divisível por 2 e 3")

    except:
      print("Você precisa digitar um número inteiro")

mostrarNumeroDivisivel()